apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-api-deployment
spec:
  selector:
    matchLabels:
      app: kuber-api
  template:
    metadata:
      labels:
        app: kuber-api
    spec:
      containers:
        - name: kuber-api
          image: kenule500/kuber-api:v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo_password
            - name: MONGODB_HOST
              value: mongodb-service.default.svc.cluster.local
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_ip
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_port
            - name: MONGODB_DATABASE
              value: docker
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-api-service
spec:
  selector:
    app: kuber-api
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 3000
