apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo_username: a2VudWxlCg==
  mongo_password: a2VudWxlCg==
#  mongo_username: a2VudWxlCg==
#   mongo_password: a2VudWxlNTAwCg==
